name: Issue Welcome
description: Add label and welcome comment

runs:
  using: "composite"
  steps:
    - name: Run welcome script
      shell: bash
      run: node .github/actions/issue-welcome/script.mjs
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}