[lint]
# E902: IOError, E999: SyntaxError
# F632: use of 'is' for literals (often a logic bug)
# F701-F723: Syntax-related errors in strings/f-strings
select = ["E9", "F63", "F7", "F82"]

# This ensures it ignores everything else (style, sorting, unused imports)
ignore = []
